### ISSUE TITLE
cache/index file for cases

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/kraus-static#16]
in order to overcome some (intended) short comings of the ARCHE-API it might be a good idea to create some cache/index file for the cases which can easily processed by any frontend application

something like a JSON file providing information about ALL Cases
* case title
* amount of docs
* start date
* end date
* keywords
* related person/places

such a file could be fetched (either on build time) or on run time from ARCHE and used for query interfaces as well as statistics about the cases to answer questions like

* give me all cases with person x in role y between YYYY and YYYY

**Comment by bellerophons-pegasus** [comment]
I'm not sure if I am a bit too naive: but couldn't you just combine ARCHE API with ARCHE full text search?
I.e. use ARCHE API to filter for the initial results set and then on that do the full text search?

**Comment by csae8092** [comment]
first iteration of above mentioned script is done, see here for the result https://github.com/acdh-oeaw/kraus-static/blob/master/cases-index.json

@bellerophons-pegasus I'm afraid fulltext search is not precise enough, lets say a case is realted with two actors but different roles; I can query for docs with actor A (ARCHE-MD) and FT seach contains role B, but I don't know if person A is really realted through role B (because it could also be person B in this case)

**Comment by csae8092** [comment]
added info about related orgs (Gerichte)
```xml
<listOrg>
       <org role="https://vocabs.acdh.oeaw.ac.at/legalkraus/v1.0/B.I.GER" ref="#pmb36842">
            <orgName>Landesgericht für Strafsachen</orgName>
            <ab type="keyword">Gerichtliche Institution</ab>
       </org>
</listOrg>
``` 
needed for

> Zweite Liste: »Beteiligte Gerichte«
Vocabs: »Beteiligter Akteur / Beteiligte Akteurin → Institution → Gerichtliche Institution«, Ergebnis als Liste der Fälle
