### ISSUE TITLE
provide GH-Workflow for binay ingest

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/kraus-static#5]
- [x] process and copy XML/TEIs into a dedicated folder "currently called ./hansi", but should be renamed into `to_ingest`
- [x] adapt https://github.com/acdh-oeaw/arche-ingest/blob/master/import_binary_sample.php to work with command lines params, passing in arche-endpoint; credentials, `to_ingest` director (which defaults to `to_ingest`), and `container to uri prefix`; which in the current case would be `https://id.acdh.oeaw.ac.at/legalkraus
- [x] run the ingest script

**Comment by zozlak** [comment]
arche-ingest 1.0.0 provides metadata and binary ingestion scripts which can be fully configured by passing parameters on the command line (see https://github.com/acdh-oeaw/arche-ingest#running-inside-github-actions and the second scenario described on https://github.com/acdh-oeaw/arche-ingest#usage). It means we don't need custom ingestion scripts inside this repository any more :-)

Our dependencies installation code should be `composer require "acdh-oeaw/arche-ingest:^1"` now and then we can run metadata/binary ingestion with, respectively,
```bash
vendor/bin/arche-import-metadata rdfFile repoUrl user password
vendor/bin/arche-import-binary dataDir idPrefix repoUrl user password
```
Both scripts support tons of optional parameters allowing to tune up the ingestion config, see
```
vendor/bin/arche-import-metadata -h
vendor/bin/arche-import-binary -h
```

**Comment by zozlak** [comment]
73e3a9d51e12c8adb9561a2cc25ff3fe598a4751 provides a first attempt
